ALTER TABLE leagues
ADD COLUMN IF NOT EXISTS show BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE seasons
ADD COLUMN IF NOT EXISTS show BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_leagues_show ON leagues (show);
CREATE INDEX IF NOT EXISTS idx_seasons_show ON seasons (show);